
export const ADD_CITY_TO_THE_LIST = 'ADD_CITY_TO_THE_LIST';

export const DELETE_DATA = 'DELETE_DATA';

export const DELETE_CITY = 'DELETE_CITY';

export const CHANGE_INPUT = 'CHANGE_INPUT';

export const FETCH_CITY = 'FETCH_CITY';

export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';

export const FETCH_CITY_ERROR = 'FETCH_CITY_ERROR';
